############################################################################
## Beets Configuration file.
## ~./config/beets/config.yaml
#############################################################################

### Global Options
library: ~/Audio/.musiclibrary.db
directory: ~/Audio/
plugins:
    # Autotagger Extensions
    - fromfilename
    # Metadata Plugins
    - edit
    - fetchart
    - embedart
    - ftintitle
    - lastgenre
    - mbsync
    # Path Format Plugins
    - inline
    # Interoperability
    - badfiles
    - play
    # Miscellaneous Plugins
    - convert
    - duplicates
    - export
    - fuzzy
    - info
    - missing
    - random
    - web
    # Other/External Plugins
    # - copyartifacts
    # - check

threaded: yes

per_disc_numbering: true

# General Configuration
ui:
    color: yes

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    log: ~/Audio/.beet.log
    bell: yes
    languages: en jp de 

aunique:
    disambuguators: media mastering label catalognum albumdisambig releasegroupdisambig

match:
    preferred:
        media: ['Vinyl', 'CD', 'Digital Media|File']

# Done in order listed. Default is special and will always go at the end.
# e.g. If I had an album with the albumtype $soundtrack and $compilation
# Then the path that matchs first takes precedence.
paths:
    default: Music/$albumartist/($year) $album%aunique{} $ep$single$live$bootleg/%if{$multidisc,Disc $disc/}$track. $title
    singleton: Music/Non-Album/$artist/$title
    vinylorcassette:1: Music/$albumartist/($year) $album%aunique{} $ep$single$live$vinyl$cassette$bootleg/%if{$multidisc,Disc $disc/}$track_alt. $title
    albumtype:soundtrack: Original Sound Tracks (OST)/$album%aunique{} ($year)/%if{$multidisc,Disc $disc/}$track. $artist - $title
    comp: Compilations/$album%aunique{} ($year) $ep$single$live$bootleg/%if{$multidisc,Disc $disc/}$track. $artist - $title
    albumtype:other: Other/$albumartist/$album%aunique{} $ep$single$live$bootleg ($year)/%if{$multidisc,Disc $disc/}$track. $title
    albumtype:audiobook: Audiobooks/$artist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track. $title
    # Add christmas=1 while importing to add to Christmas Music Collection
    christmas:1: Christmas Music Collection/$artist - $title

# Plugin Configurations

# Beets will remove empty directory after import if these are the only things left in it
# Currently isn't used in here by default because we copy instead of move files
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", "*.m3u8", "*.sfv"]
    
fetchart:
    store_source: yes

embedart:
    # I dont want album art auto-embedded
    auto: no

convert:
# auto: yes
    copy_album_art: yes
    album_art_maxwidth: 600
    dest: ~/Audio/Music [Mobile version]/
    embed: yes
    never_convert_lossy_files: yes
    format: mp3
    formats:
        mp3:
            command: ~/.scripts/flac-to-mp3.sh $source $dest
            extension: mp3
        opus:
            command: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
            extension: opus

            # extension opus.ogg
            # Above is to work around android media scanner, opus is included 
            # in the file extension for making it easier on me in the future
            # when android media scanner picks up opus extensions properly

copyartifacts:
    extensions: .cue .CUE .log .LOG .jpg .jpeg .png .accurip .md5 .txt
    print_ignored: yes

lastgenre:
    count: 5

item_fields:
    multidisc: 1 if disctotal > 1 else 0
    vinylorcassette: 1 if media in ['12" Vinyl', '7" Vinyl', 'Vinyl', 'Cassette'] else 0
    vinyl: u'[Vinyl]' if media in ['12" Vinyl', '7" Vinyl', 'Vinyl'] else ''
    cassette: u'[Cassette]' if media in ['Cassette'] else ''
    bootleg: u'[Bootleg]' if albumstatus in ['Bootleg'] else ''
    ep: u'[EP]' if albumtype == 'ep' else ''
    single: u'[Single]' if albumtype == 'single' else ''
    live: u'[Live]' if albumtype == 'live' else ''

play:
    command: /usr/bin/deadbeef
